---
title: Publications
date: 2017-12-08
---


<div>
<h2>
<span>Published (*peer-reviewed)</span>
</h2>
</div> 

- (*)A Race to the Middle. The Politics of Interstate Cost Distribution and Welfare State Expansion. The Journal of Politics, forthcoming
- (*)Taking the Initiative! Direct Democracy, Coalition Governments, and Welfare State Expansion, Journal of European Social Policy., forthcoming
- (*)[Measuring the Impacts of Colonialism: A New Data Set for the Countries of Africa and Asia. Journal of World-Systems Research, 23(1), 2017, 156-190 (with Patrick Ziltener and Daniel Kuenzler)](http://jwsr.pitt.edu/ojs/index.php/jwsr/article/download/683/937)

<div>
<h2>
<span>Other Publications (*peer-reviewed)</span>
</h2>
</div> 

- (*)[Europäische Integration auf Unternehmensebene: Die Schweizer Beteiligung an Europäischen Betriebsräten (EBR). Swiss Journal of Sociology, 42(1), 2016, p. 159–174 (with Patrick Ziltener and Heinz Gabathuler)](https://www.degruyter.com/view/j/sjs.2016.42.issue-1/sjs-2016-0008/sjs-2016-0008.xml)
- (*)[QCA, the Truth Table Analysis and Large-N Survey Data: The Benefits of Calibration and the Importance of Robustness Tests. \textit{COMPASSS Working Paper Series} 2014-79. (with Patrick Emmenegger and Dominik Schraff)](http://www.compasss.org/wpseries/EmmeneggerSchraffWalter2014.pdf)

<div>
<h2>
<span>Unter Review</span>
</h2>
</div>  

- A Disproportional Threat. The Adoption of Proportional Representation in Switzerland (with Patrick Emmenegger), R\&R
- Swiss Cantonal Governments 1848-2017. A new Dataset. (with Patrick Emmenegger)
- Majority Protection: The Origins of Distorted Proportional Representation (with Patrick Emmenegger)
- The Social Origins of Christian Democracy. Rural-Urban Migration and the Rise of the Catholic Workers’ Movement

<div>
<h2>
<span>Working Papers</span>
</h2>
</div> 


- A Socialist Threat? Radical Party Entry and the Formation of Electoral Alliances in Majoritarian Systems 
- Interest Mediation or Front Line? Socialist Electoral Mobilization and the Growth of the Catholic Workers’ Movement
- Intra-Elite Competition and the Origins of Direct Taxation (with Patrick Emmenegger and Lucas Leemann)
- Beyond the Neolithic Revolution. Endogenous Political Development, External Domination and the Formation of Pre-Colonial and Colonial States.
- When Dominant Parties Adopt PR. The Mysterious Case of Belgium (with Patrick Emmenegger).

<div>
<h2>
<span>Work in Progress</span>
</h2>
</div> 

- Initiating Welfare Competition. How the Freedom of Movement for the Poor was introduced (with Cecilia Bruzelius)
- The Adoption of Personal Income Taxation in the Swiss Cantons [Working Title] (with Patrick Emmenegger and Lucas Leemann)
- How Socialism Changed Politics. Large-Scale Evidence from District Competition and Parliamentary Debates in Imperial Germany using Quantitative Text Analysis
- Electoral System Change, Political Competition and Targeted Elite Mobilization
- Persisting Inequality. The Structure of the World Income Distribution 1975-2016 (with Patrick Ziltener)
- The Abolition of Feudal Taxation across Europe [Working Title]
- Wasted Votes? Electoral Competition, Vote Defection, and Strategic Third Party Entry in Single Member Districts
- The Black Coalition. Why the German Reich Adopted Social Insurance


