---
title: Research
date: 2017-09-22
---

### Research Interests

I'm interested in a comparative politics, comparative political economy and social science methodology. More precisely, my main research interests are:

- Population movements, inter-jurisdictional cooperation/competition and social spending. In particular, I'm interested in how eligibility restrictions affect social spending provision of jurisdictions and why such restrictions are introduced/abolished. 
- The formation of political parties and how they affect the behavior of established political parties.
- The transformation of political systems with focus on electoral systems and representative bodies.
- The link between electoral systems and political-economic institutions as well as redistribution.
- The evolution of political units, especially the formation of states

I have published with others on a number of different topics such as QCA or the impact of colonialism. In addition, I have supported research projects with regard to data collection and statistical analysis. However, the projects I'm working on are the following: 

# The Evolution of Taxation

In a project with [Patrick Emmenegger](https://pemmenegger.com) and [Lucas Leemann](https://lucasleemann.ch/), we investigate how the composition of public revenue evolved during the 19th and 20th century and how political institutions shape taxation with focus on income taxation in the Swiss cantons 1830-1980. In addition, I'm also interested in the driving forces behind abolition of feudal taxation during the first part of the 19th century in Europe. Future projects will focus on early democratization in Europe, electoral/parliamentary institutions, and public spending patterns.

# Electoral Systems Choice, Political Competition and Policy Making

In the ongoing project, I work on the introduction of proportional representation, multiparty competition in single and multimember district majoritarian electoral systems, the effects of electoral systems on turnout and political competition, and the formation and electoral strategies of parties. The focus of the project is currently on Switzerland and the Swiss cantons but I'm in the process of collecting data for other European countries in the 19th and early 20th century. Current and future projects address the introduction of PR in Belgium and how electoral advances of radical parties affect electoral strategies of established parties, legislative behavior of MPs and policy making in general.

# Federalism, Direct Democracy and Welfare State Expansion

The topic of my PhD dissertation. In the project, I have been investigating how sub-national jurisdictions manage to prevent a race to bottom with regard to social security provision via interstate cooperation. In addition, I have focused how direct democratic instruments, namely initiatives, influence the provision of social expenditure under small and large coalitions. Moreover, I have also addressed the question of how the Swiss cantons achieved full health insurance coverage during the 20th century in the absence of a mandatory insurance law on the national level. The research was accompained by an extensive data collection, covering new data on the party composition of cantonal parliaments and governments, social policy laws, and insurance coverage in the Swiss cantons in the 19th and 20th century. The results of my PhD are forthcoming in the Journal of Politics and the Journal of European Social Policy.

In a follow-up project, Cecilia Bruzelius and I are focusing on the question why barriers against the movement of the poor were abolished in Federal States.