---
title: "Teaching"
date: 2017-12-08
---
2018 

- The Politics of Electoral Systems: Political Conflict and Representation, Seminar for MA Students, University of St. Gallen (Spring Term)

2017 

- Causal Arguments and Analysis: Guest lecture invited by Prof. Patrick Emmenegger, University of St. Gallen (Spring Term) 

2013-2016 (Teaching Assistant at the University of St. Gallen, Switzerland)

- Qualitative Methods (Prof. James Davis/Prof. Klaus Dingwerth)
- Quantitative Methods (Prof. Daniele Caramani/Prof. Oliver Westerwinter)
- Research Design (Prof. Patrick Emmenegger)
- QCA (Prof. Patrick Emmenegger)
- Concept and Measurement (Prof. Patrick Emmenegger)

2011-2012 (Teaching Assistant at the University of Zurich, Switzerland)

-Vertiefung Theorien der Gender Studies (Prof. Bettina Dennerlein; Spring Term 2012)
- Theorien der Gender Studies: Eine Einführung (Prof. Bettina Dennerlein; Autumn Term 2011)

2009–2010 (Teaching Assistant at the University of Jena, Germany)

- Schlüsselbegriffe der Arbeits-, Industrie- und Wirtschaftssoziologie (Prof. Michael Behr; Winter Term 2009/2010)
- Einführung in die Makrosoziologie (Prof. Stephan Lessenich; Summer Term 2009)